@extends('admin.layouts.app')

@section('title', 'Reports History')
@section('page-title', 'Reports Management')
@section('page-description', 'Manage generated performance, activity, content, and system summaries.')

@section('content')
<div class="card border-0 shadow-sm p-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h5 class="mb-0">Reports Index</h5>
        <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#generateReportModal">
            <i class="fa-solid fa-plus me-1"></i>Generate New Report
        </button>
    </div>

    <div class="table-responsive">
        <table class="table align-middle">
            <thead class="table-light">
                <tr>
                    <th>Report Name</th>
                    <th>Type</th>
                    <th>Period</th>
                    <th>Status</th>
                    <th>Generated By</th>
                    <th>Generated At</th>
                    <th class="text-end">Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reports as $report)
                    <tr>
                        <td>
                            <a href="{{ route('admin.reports.show', $report->id) }}" class="fw-semibold text-decoration-none">
                                {{ $report->report_name }}
                            </a>
                        </td>
                        <td><span class="badge bg-secondary">{{ $report->report_type->value }}</span></td>
                        <td>{{ $report->period->value }}</td>
                        <td>
                            <span class="badge @if($report->status->value === 'completed') bg-success @elseif($report->status->value === 'failed') bg-danger @else bg-warning @endif">
                                {{ $report->status->value }}
                            </span>
                        </td>
                        <td>{{ $report->generator?->name ?? 'System' }}</td>
                        <td>{{ $report->generated_at?->toDateTimeString() ?? 'N/A' }}</td>
                        <td class="text-end">
                            <div class="btn-group">
                                <a href="{{ route('admin.reports.show', $report->id) }}" class="btn btn-outline-secondary btn-sm" title="View"><i class="fa-solid fa-eye"></i></a>
                                @if($report->file_path)
                                    <a href="{{ route('admin.reports.download', $report->id) }}" class="btn btn-outline-success btn-sm" title="Download"><i class="fa-solid fa-download"></i></a>
                                @endif
                                <form action="{{ route('admin.reports.destroy', $report->id) }}" method="POST" onsubmit="return confirm('Are you sure you want to delete this report?')" class="d-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-outline-danger btn-sm" title="Delete"><i class="fa-solid fa-trash"></i></button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" class="text-center py-4">No reports generated yet.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="mt-3">
        {{ $reports->links() }}
    </div>
</div>

<!-- Generate Report Modal -->
<div class="modal fade" id="generateReportModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <form action="{{ route('admin.reports.generate') }}" method="POST" class="modal-content">
            @csrf
            <div class="modal-header">
                <h5 class="modal-title">Generate Report</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label class="form-label">Report Name</label>
                    <input type="text" name="report_name" class="form-control" placeholder="e.g. Monthly SEO Review" required />
                </div>
                <div class="mb-3">
                    <label class="form-label">Report Type</label>
                    <select name="report_type" class="form-select" required>
                        <option value="dashboard">Dashboard</option>
                        <option value="activity">Activity Logs</option>
                        <option value="users">Users</option>
                        <option value="content">Content</option>
                        <option value="seo">SEO</option>
                        <option value="media">Media</option>
                        <option value="system">System Health</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label">Period</label>
                    <select name="period" class="form-select" required>
                        <option value="daily">Daily</option>
                        <option value="weekly">Weekly</option>
                        <option value="monthly" selected>Monthly</option>
                        <option value="yearly">Yearly</option>
                        <option value="custom">Custom</option>
                    </select>
                </div>
                <div class="row g-2 mb-3">
                    <div class="col">
                        <label class="form-label">Start Date</label>
                        <input type="date" name="start_date" class="form-control" required />
                    </div>
                    <div class="col">
                        <label class="form-label">End Date</label>
                        <input type="date" name="end_date" class="form-control" required />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Generate</button>
            </div>
        </form>
    </div>
</div>
@endsection
